name: raftup_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - anyio=4.2.0
  - appnope=0.1.3
  - apptools=5.3.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - bleach=4.1.0
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - configobj=5.0.9
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - envisage=7.0.4
  - et_xmlfile=2.0.0
  - executing=0.8.3
  - expat=2.7.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - glib=2.84.0
  - glib-tools=2.84.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h11=0.14.0
  - harfbuzz=11.1.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=75.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.28.0
  - ipython=8.27.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - json5=0.9.6
  - jsoncpp=1.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp17=17.0.6
  - libclang-cpp18.1=18.1.8
  - libclang13=21.1.0
  - libcurl=8.17.0
  - libcxx=21.1.7
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libllvm17=17.0.6
  - libllvm18=18.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopus=1.5.2
  - libpng=1.6.51
  - libpq=17.7
  - libsodium=1.0.18
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtheora=1.1.1
  - libtiff=4.7.1
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - loguru=0.7.3
  - lz4-c=1.10.0
  - markupsafe=2.1.3
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.1.6
  - mayavi=4.8.3
  - mistune=2.0.4
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - notebook-shim=0.2.3
  - nspr=4.38
  - nss=3.118
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openpyxl=3.1.5
  - openssl=3.6.0
  - overrides=7.4.0
  - packaging=24.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.44
  - pexpect=4.8.0
  - pip=24.2
  - pixman=0.46.4
  - platformdirs=3.10.0
  - ply=3.11
  - proj=9.6.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.3.1
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyface=8.0.0
  - pygments=2.15.1
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qhull=2020.2
  - qt-main=5.15.15
  - qt6-main=6.9.0
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=75.1.0
  - sip=6.14.0
  - six=1.16.0
  - snappy=1.2.2
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.51.1
  - stack_data=0.2.0
  - tbb=2022.3.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.3.0
  - tornado=6.4.1
  - traitlets=5.14.3
  - traits=7.0.2
  - traitsui=8.0.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - unicodedata2=17.0.0
  - utfcpp=4.0.8
  - vtk-base=9.4.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - wslink=2.5.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.8
      - aioitertools==0.12.0
      - aiosignal==1.3.1
      - anndata==0.10.9
      - array-api-compat==1.9
      - asciitree==0.3.3
      - botocore==1.31.17
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorcet==3.1.0
      - contourpy==1.3.0
      - dask==2024.9.1
      - dask-expr==1.1.15
      - dask-image==2024.5.3
      - datashader==0.16.3
      - distributed==2024.9.1
      - docrep==0.3.2
      - fasteners==0.19
      - fbpca==1.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2023.6.0
      - geopandas==1.0.1
      - geosketch==1.3
      - gudhi==3.10.1
      - h5py==3.12.1
      - igraph==0.11.6
      - imageio==2.35.1
      - inflect==7.4.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - jupytext==1.18.1
      - kaleido==0.2.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - legacy-api-wrap==1.4
      - leidenalg==0.10.2
      - llvmlite==0.43.0
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - matplotlib-scalebar==0.8.1
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiscale-spatial-image==1.0.1
      - natsort==8.4.0
      - networkx==3.3
      - numba==0.60.0
      - numcodecs==0.13.0
      - numpy==1.26.4
      - ome-zarr==0.9.0
      - omnipath==1.0.8
      - pandas==2.2.3
      - param==2.1.1
      - partd==1.4.2
      - paste2==1.0.1
      - patsy==0.5.6
      - pillow==10.4.0
      - pims==0.7
      - plotly==5.24.1
      - pooch==1.8.2
      - pot==0.9.4
      - pyarrow==17.0.0
      - pyct==0.5.0
      - pynndescent==0.5.13
      - pyogrio==0.10.0
      - pyparsing==3.1.4
      - pyproj==3.7.0
      - rich==13.9.1
      - s3fs==2023.6.0
      - scanpy==1.10.3
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - session-info==1.0.0
      - shapely==2.0.6
      - slicerator==1.1.0
      - sortedcontainers==2.4.0
      - spatial-image==1.1.0
      - spatialdata==0.2.3
      - squidpy==1.6.1
      - statsmodels==0.14.3
      - stdlib-list==0.10.0
      - sympy==1.13.3
      - tblib==3.0.0
      - tenacity==9.0.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - toolz==0.12.1
      - torch==2.4.1
      - torch-geometric==2.6.1
      - tqdm==4.66.5
      - typeguard==4.3.0
      - tzdata==2024.2
      - umap-learn==0.5.6
      - urllib3==1.26.20
      - validators==0.34.0
      - wrapt==1.16.0
      - xarray==2024.9.0
      - xarray-dataclasses==1.8.0
      - xarray-datatree==0.0.14
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - yarl==1.13.1
      - zarr==2.18.3
      - zict==3.0.0
prefix: /opt/anaconda3/envs/fsgw_test_paste2
